/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Views;

import Controllers.EmpleadoCtr;
import Controllers.EstadoCtr;
import Controllers.RoleCtr;
import Models.Empleado;
import Models.Estado;
import Models.Role;
import java.util.ArrayList;
import java.util.List;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class frmEmpleado extends javax.swing.JInternalFrame {
    
    EmpleadoCtr ctrol=new EmpleadoCtr();
    RoleCtr ctrolRole = new RoleCtr();
    EstadoCtr ctrolEstado = new EstadoCtr();
    
    Empleado mod = new Empleado();
    Role modRole = new Role();
    Estado modEstado = new Estado();
    
    List<Role> listaRole = ctrolRole.listaTabla(null);
    List<Estado> listaEstado = ctrolEstado.listaTabla(null);
    
    int flag=0;
    
    public frmEmpleado() {
        initComponents();
        leerTabla(null);
        limpiar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setClosable(true);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Ci", "Nombre", "Apellido", "Usuario", "Contraseña", "Role", "Estado"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                click_sobre_la_fila(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Empleado");

        jLabel2.setText("Codigo");

        jLabel3.setText("CI");

        jLabel4.setText("Nombre");

        jLabel5.setText("Apellido");

        jButton1.setText("Nuevo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Agregar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setText("Eliminar");

        jButton6.setText("Limpiar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel6.setText("Usuario");

        jLabel7.setText("Contraseña");

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jLabel8.setText("Estado");

        jLabel9.setText("Role");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                                    .addComponent(jTextField4)
                                    .addComponent(jTextField1)
                                    .addComponent(jTextField2))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox2, 0, 189, Short.MAX_VALUE)
                            .addComponent(jTextField5)
                            .addComponent(jTextField6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6)
                    .addComponent(jLabel9))
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        flag = 1;
        jTextField2.requestFocus();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(flag==1){
            int ci = Integer.parseInt(jTextField2.getText());
            String nombre = jTextField3.getText();
            String apellido = jTextField4.getText();
            String usuario = jTextField5.getText();
            String clave = jTextField6.getText();
            
            String roleBusqueda = (String) jComboBox2.getSelectedItem();
            String estadoBusqueda = (String) jComboBox1.getSelectedItem();
            List<Role> roleL = ctrolRole.listaTabla(roleBusqueda);
            List<Estado> estadoL = ctrolEstado.listaTabla(estadoBusqueda);

            int roleId=0;
            int estadoId=0;

            // Buscar el ID correspondiente al role seleccionado
            for (Role role : roleL) {
                if (role.getDescripcion().equals(roleBusqueda)) {
                    roleId = role.getId(); // Asumiendo que Role tiene un método getId()
                    break;
                }
            }

            // Buscar el ID correspondiente al estado seleccionado
            for (Estado estado : estadoL) {
                if (estado.getDescripcion().equals(estadoBusqueda)) {
                    estadoId = estado.getId(); // Asumiendo que Estado tiene un método getId()
                    break;
                }
            }

            // Ahora tienes los IDs correspondientes en roleId y estadoId
            System.out.println("Role ID: " + roleId);
            System.out.println("Estado ID: " + estadoId);
            
            ctrol.agregar(ci, nombre, apellido, usuario, clave, roleId, estadoId);
            
            limpiar();
            leerTabla(null);
        }
        if (flag == 3){
            int cod = Integer.parseInt(jTextField1.getText());
            int ci = Integer.parseInt(jTextField2.getText());
            String nombre = jTextField3.getText();
            String apellido = jTextField4.getText();
            String usuario = jTextField5.getText();
            String clave = jTextField6.getText();
            String roleBusqueda = (String) jComboBox2.getSelectedItem();
            String estadoBusqueda = (String) jComboBox1.getSelectedItem();
            List<Role> roleL = ctrolRole.listaTabla(roleBusqueda);
            List<Estado> estadoL = ctrolEstado.listaTabla(estadoBusqueda);
            int role=1;//BuscarComboBoxQuery(roleL);
            int estado=1;//BuscarComboBoxQuery(estadoL);

            ctrol.modificar(ci, nombre, apellido, usuario, clave, role, estado, cod);
            
            limpiar();            
            leerTabla(null);
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void click_sobre_la_fila(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_click_sobre_la_fila
        // TODO add your handling code here:
        Integer linea = jTable1.getSelectedRow();

        // Establecer los textos en los jTextField correspondientes
        this.jTextField1.setText(String.valueOf(jTable1.getValueAt(linea, 0)));
        this.jTextField1.setEditable(false);
        this.jTextField2.setText(String.valueOf(jTable1.getValueAt(linea, 1)));
        this.jTextField3.setText(String.valueOf(jTable1.getValueAt(linea, 2)));
        this.jTextField4.setText(String.valueOf(jTable1.getValueAt(linea, 3)));
        this.jTextField5.setText(String.valueOf(jTable1.getValueAt(linea, 4)));
        this.jTextField6.setText(String.valueOf(jTable1.getValueAt(linea, 5)));
        this.jComboBox2.setSelectedItem(jTable1.getValueAt(linea, 6));
        this.jComboBox1.setSelectedItem(jTable1.getValueAt(linea, 7));

        int i = JOptionPane.showOptionDialog(null,"Deseas Editar, Borrar o Cancelar?","Grabar",
        JOptionPane.YES_NO_CANCEL_OPTION,
        JOptionPane.QUESTION_MESSAGE,null,
        new Object[]{"Editar","Borrar","Cancelar"},"Editar");

        i=i+1;

        if (i != -1){
            if (i==1){
                flag=3;
            }
            if(i==2){
                flag=2;
                int codigo = Integer.parseInt(jTextField1.getText());
                ctrol.eliminar(codigo);
                limpiar();
                leerTabla(null);
            }
            if(i==3){
                limpiar();
                
            }
        }
    }//GEN-LAST:event_click_sobre_la_fila

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables

    public void limpiar(){
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        
        jComboBox1.removeAllItems();
        jComboBox2.removeAllItems();
        llenarComboBox(jComboBox1, listaEstado);
        llenarComboBox(jComboBox2, listaRole);
    }
    
    private void leerTabla(String dato) {
        List<Empleado> listaEmpleado = new ArrayList<>();
        listaEmpleado= ctrol.listaTabla(dato);
        
        DefaultTableModel tbm = (DefaultTableModel) jTable1.getModel();
        tbm.setColumnIdentifiers(new String[]{"Codigo","Ci","Nombre", "Apellido", "Usuario", "Clave", "Role", "Estado"});
        
        for(int i=tbm.getRowCount()-1; i>=0 ;i--){
            tbm.removeRow(i);
        }
        
        int i=0;
        for(Empleado tab : listaEmpleado){
            
            tbm.addRow(new Object[1]);
            
            jTable1.setValueAt(tab.getId(),i,0);
            jTable1.setValueAt(tab.getCi(), i, 1);
            jTable1.setValueAt(tab.getNombre(), i, 2);
            jTable1.setValueAt(tab.getApellido(), i, 3);
            jTable1.setValueAt(tab.getUsuario(), i, 4);
            jTable1.setValueAt(tab.getClave(), i, 5);
            
            Role role = ctrolRole.buscarPorId(tab.getRole());
            String estadoQuery = "est_codigo = "+String.valueOf(tab.getEstado());
            //est_descripcion like
            Estado estado = ctrolEstado.buscarPorId(estadoQuery);
            
            if (estado != null) {
                tbm.setValueAt(estado.getDescripcion(), i, 7);
            } else {
                System.out.println("Estado no encontrado para el ID: " + tab.getEstado());
            }

            if (role != null) {
                tbm.setValueAt(role.getDescripcion(), i, 6);
            } else {
                System.out.println("Role no encontrado para el ID: " + tab.getRole());
            }
            i++;
        }
        jTable1.requestFocus();

    }
    
    private void llenarComboBox(JComboBox<String> comboBox, List<?> listaItems) {
        comboBox.removeAllItems();
        comboBox.addItem("Seleccionar");

        for (Object item : listaItems) {
            if (item instanceof Role) {
                Role role = (Role) item;
                comboBox.addItem(role.getDescripcion());
            } else if (item instanceof Estado) {
                Estado estado = (Estado) item;
                comboBox.addItem(estado.getDescripcion());
            }
        }
    }
}


